### ISSUE TITLE
Daemon

### ISSUE THREAD

**Issue by siayush** [dbieber/at-scheduler#3] opened 2018-10-06 04:39 UTC
Traceback (most recent call last):
  File "/projects/at-scheduler/at/atd.py", line 13, in <module>
    import daemon.pidfile
ModuleNotFoundError: No module named 'daemon.pidfile'; 'daemon' is not a package

daemon.pidfile is not available in daemon module.

**Comment by dbieber** [comment] 2018-10-06 05:50
Ah, my use of the daemon package must of gone out of date.
If you find a fix before I do, lmk!

Edit: Nope, that wasn't it. My usage of the daemon package still works.

**Comment by siayush** [comment] 2018-10-06 06:06
Thanks, @dbieber but, there is one more question 
"at 10pm say Good evening George!" is not working.

**Comment by dbieber** [comment] 2018-10-06 06:39
The daemon has to be running for it to work.
Once we resolve the error you pointed out above, then I expect it will work again.

**Comment by siAyush** [comment] 2018-10-06 06:51
Sir, I'm new in this field can you please become my mentor.And my passion is for Machine Learning.It is very helpful for me if guide me.

**Comment by dbieber** [comment] 2018-10-06 07:08
I checked, and my usage of the daemon package still works. So, I will close this issue, but feel free to leave additional comments if you have questions.

Most likely the problem is that you don't have the dependencies installed for your root Python interpreter. Installing Python dependencies for root is unusual, but is necessary since the daemon runs as root. To resolve this, try the following series of commands:

```
# Install dependencies for root
sudo pip install apscheduler
sudo pip install parsedatetime
sudo pip install docutils
sudo pip install python-daemon
sudo pip install redis

# Start the redis server and at-daemon
sudo redis-server &
sudo mkdir -p /opt/at-scheduler
sudo python at/atd.py
```

Once you've done that, you should be able to issue commands like `at 10pm say Ayush is going to become an ML expert!`

----

As for your study of ML, here are some resources you may find useful:

Fast AI
http://fast.ai

Richard Socher's Neural Nets for Natural Language Processing:
http://cs224d.stanford.edu/syllabus.html
https://www.youtube.com/watch?v=kZteabVD8sU
https://www.youtube.com/watch?v=xhHOL3TNyJs
https://www.youtube.com/watch?v=UOGMsFw9V_w
https://www.youtube.com/watch?v=bjDbNbSbwY4
https://www.youtube.com/watch?v=k50GPWfjG7I
https://www.youtube.com/watch?v=l0k-30FNua8
https://www.youtube.com/watch?v=L8Y2_Cq2X5s
https://www.youtube.com/watch?v=nwcJuGuG-0s
Sound issue, so no video.
https://www.youtube.com/watch?v=83J3PMValS4
https://www.youtube.com/watch?v=elgkSIWm1vs

Convolutional Neural Networks for Visual Recognition
http://cs231n.stanford.edu/

David Silver's reinforcement learning class
https://www.youtube.com/watch?v=2pWv7GOvuf0, etc (should be a playlist on YouTube)

Another Deep RL Course (Can't vouch for this one)
http://rll.berkeley.edu/deeprlcourse/

Karpathy's Blog
http://karpathy.github.io/2015/05/21/rnn-effectiveness/

Distill
https://distill.pub/

Chris Olah's Blog
http://colah.github.io/

David Ha's Blog
http://otoro.net/ml/

Best of luck following your passion and studying machine learning!

**Closed as completed by dbieber** 2018-10-06 07:08 UTC

**Comment by siAyush** [comment] 2018-10-06 07:45
Sir for future help can I get your contact number or something you prefer to share with me.
Email me -- siayush.gupta@gmail.com

**Comment by siayush** [comment] 2018-10-06 13:02
When I uninstall your at-scheduler and install Linux at command using 
'sudo apt install at' it installed nicely but when I try to run it gives the following error
 "/usr/bin/python: No module named at"

**Comment by dbieber** [comment] 2018-10-06 16:48
To see what the command `at` currently refers to on your system, you can run `type at`.

To uninstall at-scheduler, the command is `pip uninstall at-scheduler` (with or without sudo, depending on how you installed it in the first place).

I'd prefer if future communications about at-scheduler take place on GitHub so that other people may benefit from the conversations. For questions about machine learning, I won't usually be the best person to ask. Quora, Twitter, or the machine learning subreddit can be good places to find discussions and other people looking to learn, and the fasi.ai course also has a good community around it (http://forums.fast.ai/). If you do need to contact me privately (though again I generally prefer public communications) you can find my public contact info in my github profile.

**Comment by siayush** [comment] 2018-10-07 04:38
Thanks @dbieber

**Comment by siayush** [comment] 2018-10-07 05:12
```
import daemon.pidfile
ModuleNotFoundError: No module named 'daemon.pidfile'; 'daemon' is not a package
```
The problem with this is that, I downloaded `daemon` tool instead of `python-daemon` .
So , when I figer out this and then install correct tool it  happen again
`No module named 'daemon.pidfile'; 'daemon' is not a package`
this time because I previously install wrong `daemon` tool and it's pycache is still is importing 
in at-scheduler because both modules `daemon` and `python-daemon` has same name at 
time of import `import daemon` so it's importing old `daemon` pycache in which pidfile attributes is not present.
Solution is for that is to delete the old pycache and import it again and it works fine.

**Comment by dbieber** [comment] 2018-10-07 06:42
I'm glad to hear you got it working.
